safe: true
permalink: /:title.html
exclude: [ assets ]
markdown: kramdown

default_theme: ribbon
default_width: 792
default_lang: ru
default_body_class: list

kramdown:
  enable_coderay: false

author:
    name: Boris Serduik
    position: Testing tools develoment
    company:
        name: Yandex
        url:  https://yandex.ru/

progress: true
